// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12uD-s5jIqrSTrntN8lFPv3xi3jLyHq0',
    appId: '1:205344315713:web:0f2533321dcc7c74cbe9c0',
    messagingSenderId: '205344315713',
    projectId: 'logicsnow',
    authDomain: 'logicsnow.firebaseapp.com',
    storageBucket: 'logicsnow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfj9sv_9WPJ1Z8JJuDgtk2_yML6eTjHlc',
    appId: '1:205344315713:android:02f8fe38df0c6d8dcbe9c0',
    messagingSenderId: '205344315713',
    projectId: 'logicsnow',
    storageBucket: 'logicsnow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXkwgookUKfXeXL3fkIqndaymlJo86CQ',
    appId: '1:205344315713:ios:7c9d5d4c9c570364cbe9c0',
    messagingSenderId: '205344315713',
    projectId: 'logicsnow',
    storageBucket: 'logicsnow.appspot.com',
    iosClientId: '205344315713-3896rljc2ninpd3g4ddoptvetah7g5ci.apps.googleusercontent.com',
    iosBundleId: 'com.krinfinity.logisticsnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXkwgookUKfXeXL3fkIqndaymlJo86CQ',
    appId: '1:205344315713:ios:838ae03dc2ffe0b8cbe9c0',
    messagingSenderId: '205344315713',
    projectId: 'logicsnow',
    storageBucket: 'logicsnow.appspot.com',
    iosClientId: '205344315713-mmjp5brnrpfeddrphths8dbdd93b6fse.apps.googleusercontent.com',
    iosBundleId: 'com.krinfinity.logisticsnow.RunnerTests',
  );
}
